<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/pruebaTecnicaTinder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**¿Que Sexo consigue mas parejas en la plataforma Tinder?**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/encuestas_tinder.csv')
df.head()

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship,Gender
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes,male
1,292883,Mobile,Mobile respondents,No,1969,0.511,No,female
2,292885,Mobile,Mobile respondents,I don't use Tinder,1090,0.283,Yes,male
3,292887,Web,Web-based respondents,Yes,0,0.000,No,female
4,292889,Web,Web-based respondents,No,0,0.000,No,female

Se filtran las filas donde el valor para la columna 'Answer' es Yes y donde el valor de la columna 'It became a Relationship' es Yes, es decir, solo los casos de exito.

In [ ]:
mask = (df['Answer'] == 'Yes') & (df['It became a Relationship'] == 'Yes')
df_sucess = df[mask]
df_sucess.shape[0]

44

In [ ]:
df_sucess.head()

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship,Gender
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes,male
6,292893,Gender,Male respondents,Yes,472,0.213,Yes,male
24,292929,University,Georgetown University,Yes,2,0.500,Yes,male
30,292941,University,Indiana University,Yes,9,0.205,Yes,male
42,292965,University,Princeton University,Yes,1,0.500,Yes,male

Cantidad de exitos por Sexo.

In [ ]:
df_sucess['Gender'].value_counts()

Gender
female    28
male      16
Name: count, dtype: int64

Se crea un nuevo DataFrame con los datos obtenidos en el paso anterior.

In [ ]:
sucess_rate_per_sex = pd.DataFrame(df_sucess['Gender'].value_counts())
sucess_rate_per_sex.head()

        count
Gender
female     28
male       16

Se crea una nueva columna para el DataFrame creado que incluya el porcentaje de exito.

In [ ]:
sucess_rate_per_sex['%'] = round(sucess_rate_per_sex['count'] / sucess_rate_per_sex['count'].sum() * 100, 2)
sucess_rate_per_sex.head()

        count      %
Gender
female     28  63.64
male       16  36.36

**¿Cual es el porcentaje de personas que consiguieron pareja usando Tinder?**

In [ ]:
df.columns

Index(['ID', 'Segment Type', 'Segment Description', 'Answer', 'Count',
       'Percentage', 'It became a Relationship', 'Gender'],
      dtype='object')

Filtrar los datos de las personas que usan la plataforma (columna Answer) y obtener el porcentaje de las personas que consiguieron pareja (columna 'It became a Relationship')

In [ ]:
usuarios_tinder = df.groupby('Answer')['It became a Relationship'].value_counts(normalize=True)
usuarios_tinder

Answer              It became a Relationship
I don't use Tinder  No                          0.715232
                    Yes                         0.284768
No                  No                          0.715232
                    Yes                         0.284768
Yes                 No                          0.708609
                    Yes                         0.291391
Name: proportion, dtype: float64

Cantidad de encuestados que utilizan Tinder

In [ ]:
tinder_users = df[df['Answer'] == 'Yes']
tinder_users.shape[0]

151

In [ ]:
tinder_users['It became a Relationship'].value_counts()

It became a Relationship
No     107
Yes     44
Name: count, dtype: int64

In [ ]:
tinder_sucess_rate = pd.DataFrame(tinder_users['It became a Relationship'].value_counts())
tinder_sucess_rate['%'] = round(tinder_sucess_rate['count'] / tinder_sucess_rate['count'].sum() * 100, 2)
tinder_sucess_rate

                          count      %
It became a Relationship
No                          107  70.86
Yes                          44  29.14

**Tomando en cuenta la totalidad de los encuestados (quienes usan y quienes no la plataforma), obtener el porcentaje de los mismos que consiguieron pareja usando Tinder**

In [ ]:
mask = (df['Answer'] == 'Yes') & (df['It became a Relationship'] == 'Yes')
sucess = df[mask]
sucess.shape[0]

44

In [ ]:
sucess_percentage = round((sucess.shape[0]) / (df.shape[0]) * 100, 2)
f'El porcentaje de encuestados que consiguieron pareja usando Tinder es: {sucess_percentage}%'

'El porcentaje de encuestados que consiguieron pareja usando Tinder es: 9.71%'