<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/pruebaTecnicaLoL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**¿Cual es el personaje tanque de League of Legends mas dificil de jugar?**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/lol_data.csv')
df.head()

,Unnamed: 0,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,...,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname,nickname
0,Aatrox,266.0,Aatrox,the Darkin Blade,2,Fighter,Tank,Blood Well,"{'hp_base': 650, 'hp_lvl': 114, 'mp_base': 0, ...",Melee,...,4800,880,{1: 'Deathbringer Stance'},"{1: 'The Darkin Blade', 2: 'The Darkin Blade 3'}",{1: 'Infernal Chains'},{1: 'Umbral Dash'},{1: 'World Ender'},"{1: 'Deathbringer Stance', 2: 'The Darkin Blad...",NaN,NaN
1,Ahri,103.0,Ahri,the Nine-Tailed Fox,2,Mage,Assassin,Mana,"{'hp_base': 590, 'hp_lvl': 104, 'mp_base': 418...",Ranged,...,3150,790,{1: 'Essence Theft'},{1: 'Orb of Deception'},{1: 'Fox-Fire'},{1: 'Charm'},{1: 'Spirit Rush'},"{1: 'Essence Theft', 2: 'Orb of Deception', 3:...",NaN,NaN
2,Akali,84.0,Akali,the Rogue Assassin,2,Assassin,NaN,Energy,"{'hp_base': 600, 'hp_lvl': 119, 'mp_base': 200...",Melee,...,3150,790,"{1: ""Assassin's Mark""}",{1: 'Five Point Strike'},{1: 'Twilight Shroud'},{1: 'Shuriken Flip'},{1: 'Perfect Execution'},"{1: ""Assassin's Mark"", 2: 'Five Point Strike',...",Akali Jhomen Tethi,NaN
3,Akshan,166.0,Akshan,the Rogue Sentinel,3,Marksman,Assassin,Mana,"{'hp_base': 630, 'hp_lvl': 107, 'mp_base': 350...",Ranged,...,4800,880,{1: 'Dirty Fighting'},{1: 'Avengerang'},{1: 'Going Rogue'},{1: 'Heroic Swing'},{1: 'Comeuppance'},"{1: 'Dirty Fighting', 2: 'Avengerang', 3: 'Goi...",NaN,NaN
4,Alistar,12.0,Alistar,the Minotaur,1,Tank,Support,Mana,"{'hp_base': 685, 'hp_lvl': 120, 'mp_base': 350...",Melee,...,1350,585,{1: 'Triumphant Roar'},{1: 'Pulverize'},{1: 'Headbutt'},{1: 'Trample'},{1: 'Unbreakable Will'},"{1: 'Triumphant Roar', 2: 'Pulverize', 3: 'Hea...",NaN,NaN

Nombres de las columnas

In [3]:
df.columns

Index(['Unnamed: 0', 'id', 'apiname', 'title', 'difficulty', 'herotype',
       'alttype', 'resource', 'stats', 'rangetype', 'date', 'patch', 'changes',
       'role', 'client_positions', 'external_positions', 'damage', 'toughness',
       'control', 'mobility', 'utility', 'style', 'adaptivetype', 'be', 'rp',
       'skill_i', 'skill_q', 'skill_w', 'skill_e', 'skill_r', 'skills',
       'fullname', 'nickname'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          172 non-null    object
 1   id                  172 non-null    float64
 2   apiname             172 non-null    object
 3   title               172 non-null    object
 4   difficulty          172 non-null    int64
 5   herotype            172 non-null    object
 6   alttype             144 non-null    object
 7   resource            167 non-null    object
 8   stats               172 non-null    object
 9   rangetype           172 non-null    object
 10  date                172 non-null    object
 11  patch               172 non-null    object
 12  changes             172 non-null    object
 13  role                172 non-null    object
 14  client_positions    172 non-null    object
 15  external_positions  172 non-null    object
 16  damage              172 non-null    int64
 17  toughness           172 non-null    int64
 18  control             172 non-null    int64
 19  mobility            172 non-null    int64
 20  utility             172 non-null    int64
 21  style               172 non-null    int64
 22  adaptivetype        172 non-null    object
 23  be                  172 non-null    int64
 24  rp                  172 non-null    int64
 25  skill_i             172 non-null    object
 26  skill_q             172 non-null    object
 27  skill_w             172 non-null    object
 28  skill_e             172 non-null    object
 29  skill_r             172 non-null    object
 30  skills              170 non-null    object
 31  fullname            43 non-null     object
 32  nickname            14 non-null     object
dtypes: float64(1), int64(9), object(23)
memory usage: 44.5+ KB

Tipo de dato que tiene cada columna

In [5]:
df.dtypes

Unnamed: 0             object
id                    float64
apiname                object
title                  object
difficulty              int64
herotype               object
alttype                object
resource               object
stats                  object
rangetype              object
date                   object
patch                  object
changes                object
role                   object
client_positions       object
external_positions     object
damage                  int64
toughness               int64
control                 int64
mobility                int64
utility                 int64
style                   int64
adaptivetype           object
be                      int64
rp                      int64
skill_i                object
skill_q                object
skill_w                object
skill_e                object
skill_r                object
skills                 object
fullname               object
nickname               object
dtype: object

Todos los tipos de heroes

In [6]:
df['herotype'].value_counts()

herotype
Fighter     49
Mage        37
Marksman    28
Tank        24
Assassin    17
Support     17
Name: count, dtype: int64

Los valores que representan la dificultad de cada heroe

In [7]:
df['difficulty'].value_counts()

difficulty
2    93
1    51
3    28
Name: count, dtype: int64

Se filtra por tipo de heroe y por dificultad maxima

In [8]:
mask = (df['herotype'] == 'Tank') & (df['difficulty'] == 3)
most_difficult_tank = df[mask]
most_difficult_tank.shape[0]

1

In [9]:
most_difficult_tank[['apiname', 'title', 'difficulty', 'herotype']]

   apiname                 title  difficulty herotype
56  KSante  the Pride of Nazumah           3     Tank