<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/TT_stackoverflow_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [194]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [195]:
df = pd.read_csv('/content/results.csv', low_memory=False)
schema = pd.read_csv('/content/schema.csv')
pd.set_option('display.max_columns', None)

In [196]:
df.shape

(49191, 172)

In [197]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 357.8 MB

In [198]:
for c in df.select_dtypes('object'):
  df[c] = df[c].astype('category')

In [199]:
for i in df.select_dtypes('integer'):
  df[i] = pd.to_numeric(df[i], downcast='integer')

In [200]:
for f in df.select_dtypes('float'):
  df[f] = pd.to_numeric(df[f], downcast='float')

In [201]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: category(119), float32(50), float64(2), int32(1)
memory usage: 57.6 MB

In [202]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_')
)
df.columns

Index(['responseid', 'mainbranch', 'age', 'edlevel', 'employment',
       'employmentaddl', 'workexp', 'learncodechoose', 'learncode',
       'learncodeai',
       ...
       'aiagentorchestration', 'aiagentorchwrite', 'aiagentobservesecure',
       'aiagentobswrite', 'aiagentexternal', 'aiagentextwrite', 'aihuman',
       'aiopen', 'convertedcompyearly', 'jobsat'],
      dtype='object', length=172)

In [203]:
nulls_count = df.isnull().sum()
nulls_count[nulls_count > 0].sort_values(ascending=False)

aiagentobswrite      48927
sotagswant_entry     48761
sotagshaveentry      48733
aimodelswantentry    48716
aiagentorchwrite     48713
                     ...
employmentaddl        4316
learncodeai           3990
learncodechoose       2333
edlevel               1042
employment             852
Length: 169, dtype: int64

In [204]:
nulls_percentage = df.isnull().mean()*100
nulls_percentage[nulls_percentage > 0].sort_values(ascending=False)

aiagentobswrite      99.463316
sotagswant_entry     99.125856
sotagshaveentry      99.068935
aimodelswantentry    99.034376
aiagentorchwrite     99.028278
                       ...
employmentaddl        8.773963
learncodeai           8.111240
learncodechoose       4.742737
edlevel               2.118274
employment            1.732024
Length: 169, dtype: float64

In [205]:
duplicates_sum = df.duplicated().sum()
duplicates_sum

np.int64(0)

In [206]:
duplicates_percentage = (df.duplicated().sum()/df.shape[0]) * 100
duplicates_percentage

np.float64(0.0)

In [207]:
# show_duplicates = df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head()
# show_duplicates

In [208]:
# df = df.drop_duplicates()

**¿Cuanto cobra un desarrollador que trabaja remoto vs un desarrollador que trabaja presencial?**

In [209]:
schema.head()

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR

In [210]:
schema['qname'].unique()

array(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize',
       'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse',
       'Country', 'Currency', 'CompTotal', 'Language', 'Database',
       'Platform', 'Webframe', 'Embedded', 'MiscTech', 'ToolsTech',
       'NEWCollabTools', 'OpSys', 'OfficeStackAsync', 'OfficeStackSync',
       'AISearchDev', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen',
       'AIAcc', 'AIComplex', 'AITool', 'AINext', 'AIThreat', 'AIEthics',
       'AIChallenges', 'TBranch', 'ICorPM', 'WorkExp', 'Knowledge',
       'Frequency', 'TimeSearching', 'TimeAnswering', 'Frustration',
       'ProfessionalTech', 'ProfessionalCloud', 'ProfessionalQuestion',
       'Industry', 'JobSat', 'JobSatPoints', 'SOTeamsUsage',
       'SurveyLength', 'SurveyEase', 'Knowledge_1', 'Knowledge_2',
       'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6',
       'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'JobSatPoints_1', 'JobSatPoints_4',
       'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7',
       'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10',
       'JobSatPoints_11'], dtype=object)

In [211]:
schema.loc[schema['qname'] == 'RemoteWork']

,qid,qname,question,force_resp,type,selector
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR

In [212]:
df.head(1)

,responseid,mainbranch,age,edlevel,employment,employmentaddl,workexp,learncodechoose,learncode,learncodeai,ailearnhow,yearscode,devtype,orgsize,icorpm,remotework,purchaseinfluence,techendorseintro,techendorse_1,techendorse_2,techendorse_3,techendorse_4,techendorse_5,techendorse_6,techendorse_7,techendorse_8,techendorse_9,techendorse_13,techendorse_13_text,techoppose_1,techoppose_2,techoppose_3,techoppose_5,techoppose_7,techoppose_9,techoppose_11,techoppose_13,techoppose_16,techoppose_15,techoppose_15_text,industry,jobsatpoints_1,jobsatpoints_2,jobsatpoints_3,jobsatpoints_4,jobsatpoints_5,jobsatpoints_6,jobsatpoints_7,jobsatpoints_8,jobsatpoints_9,jobsatpoints_10,jobsatpoints_11,jobsatpoints_13,jobsatpoints_14,jobsatpoints_15,jobsatpoints_16,jobsatpoints_15_text,aithreat,newrole,toolcountwork,toolcountpersonal,country,currency,comptotal,languagechoice,languagehaveworkedwith,languagewanttoworkwith,languageadmired,languageshaveentry,languageswantentry,databasechoice,databasehaveworkedwith,databasewanttoworkwith,databaseadmired,databasehaveentry,databasewantentry,platformchoice,platformhaveworkedwith,platformwanttoworkwith,platformadmired,platformhaveentry,platformwantentry,webframechoice,webframehaveworkedwith,webframewanttoworkwith,webframeadmired,webframehaveentry,webframewantentry,devenvschoice,devenvshaveworkedwith,devenvswanttoworkwith,devenvsadmired,devenvhaveentry,devenvwantentry,sotagshaveworkedwith,sotagswanttoworkwith,sotagsadmired,sotagshaveentry,sotagswant_entry,opsyspersonal_use,opsysprofessional_use,officestackasynchaveworkedwith,officestackasyncwanttoworkwith,officestackasyncadmired,officestackhaveentry,officestackwantentry,commplatformhaveworkedwith,commplatformwanttoworkwith,commplatformadmired,commplatformhaveentr,commplatformwantentr,aimodelschoice,aimodelshaveworkedwith,aimodelswanttoworkwith,aimodelsadmired,aimodelshaveentry,aimodelswantentry,soaccount,sovisitfreq,soduration,sopartfreq,so_dev_content,so_actions_1,so_actions_16,so_actions_3,so_actions_4,so_actions_5,so_actions_6,so_actions_9,so_actions_7,so_actions_10,so_actions_15,so_actions_15_text,socomm,sofriction,aiselect,aisent,aiacc,aicomplex,aitoolcurrently_partially_ai,aitooldon't_plan_to_use_ai_for_this_task,aitoolplan_to_partially_use_ai,aitoolplan_to_mostly_use_ai,aitoolcurrently_mostly_ai,aifrustration,aiexplain,aiagents,aiagentchange,aiagent_uses,agentusesgeneral,aiagentimpactsomewhat_agree,aiagentimpactneutral,aiagentimpactsomewhat_disagree,aiagentimpactstrongly_agree,aiagentimpactstrongly_disagree,aiagentchallengesneutral,aiagentchallengessomewhat_disagree,aiagentchallengesstrongly_agree,aiagentchallengessomewhat_agree,aiagentchallengesstrongly_disagree,aiagentknowledge,aiagentknowwrite,aiagentorchestration,aiagentorchwrite,aiagentobservesecure,aiagentobswrite,aiagentexternal,aiagentextwrite,aihuman,aiopen,convertedcompyearly,jobsat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0

In [213]:
len(df['remotework'].unique())

6

In [214]:
df['remotework'].unique()

['Remote', 'Hybrid (some in-person, leans heavy to flexib..., NaN, 'In-person', 'Hybrid (some remote, leans heavy to in-person)', 'Your choice (very flexible, you can come in w...]
Categories (5, object): ['Hybrid (some in-person, leans heavy to flexib..., 'Hybrid (some remote, leans heavy to in-person)',
                         'In-person', 'Remote',
                         'Your choice (very flexible, you can come in w...]

In [215]:
df['remotework'] = df['remotework'].astype(str)

In [216]:
df['remotework'].unique()

array(['Remote', 'Hybrid (some in-person, leans heavy to flexibility)',
       np.str_('nan'), 'In-person',
       'Hybrid (some remote, leans heavy to in-person)',
       'Your choice (very flexible, you can come in when you want or just as needed)'],
      dtype=object)

In [217]:
# Remote, Hybrid (some in person, flexibility), In-person, Hybrid (some remote, heavy in person), Your Choice

Dataframe con los encuestados que afirmaron trabajar en remoto o significativamente mas en remoto. Se excluyen las filas donde la columna convertedcompyearly almacena un valor nulo.

In [218]:
mask_remote = ((df['remotework'] == 'Remote') | (df['remotework'] == 'Hybrid (some in-person, leans heavy to flexibility)') | (df['remotework'] == 'Your choice (very flexible, you can come in when you want or just as needed)')) & (df['convertedcompyearly'].notna())
df_remote = df.loc[mask_remote][['remotework', 'convertedcompyearly']]

In [219]:
df_remote.shape[0]

13694

In [220]:
remote_total = df_remote.groupby('remotework')['convertedcompyearly'].agg(['median', 'count']).sort_values(by='median', ascending=False)
remote_total

                                                     median  count
remotework
Remote                                              88492.0   7126
Hybrid (some in-person, leans heavy to flexibil...  80966.0   3815
Your choice (very flexible, you can come in whe...  75410.0   2753

In [221]:
print(f'Encuestados que afirmaron trabajar en remoto: {remote_total.iloc[0]['count'].sum()}.')
print(f'Salario medio anual de los encuestados que trabajan remoto: {remote_total.iloc[0]['median']} dolares.')
print(f'Encuestados que afirmaron trabajar en remoto o significativamente mas en remoto: {remote_total['count'].sum()}.')

Encuestados que afirmaron trabajar en remoto: 7126.0.
Salario medio anual de los encuestados que trabajan remoto: 88492.0 dolares.
Encuestados que afirmaron trabajar en remoto o significativamente mas en remoto: 13694.

Dataframe con los datos de los encuestados que afirmaron trabajar presencial o significativamente mas en presencial. Se excluyen las filas donde la columna convertedcompyearly almacena un valor nulo.

In [222]:
mask_in_person = ((df['remotework'] == 'In-person') | (df['remotework'] == 'Hybrid (some remote, leans heavy to in-person)')) & (df['convertedcompyearly'].notna())
df_in_person = df.loc[mask_in_person][['remotework', 'convertedcompyearly']]

In [223]:
df_in_person.shape[0]

7402

In [224]:
in_person_total = df_in_person.groupby('remotework')['convertedcompyearly'].agg(['median', 'count']).sort_values(by='median', ascending=False)
in_person_total

                                                 median  count
remotework
Hybrid (some remote, leans heavy to in-person)  72958.0   4203
In-person                                       46406.0   3199

In [225]:
print(f'Encuestados que afirmaron trabajar presencial: {in_person_total.iloc[1]['count'].sum()}')
print(f'Salario medio anual de los encuestados que trabajan presencial: {in_person_total.iloc[1]['median']} dolares.')
print(f'Encuestados que afirmaron trabajar presencial o significativamente mas en regimen presencial: {in_person_total['count'].sum()}.')

Encuestados que afirmaron trabajar presencial: 3199.0
Salario medio anual de los encuestados que trabajan presencial: 46406.0 dolares.
Encuestados que afirmaron trabajar presencial o significativamente mas en regimen presencial: 7402.

Se obtiene el salario medio para ambos grupos de encuestados, quienes afirmaron trabajar mas en remoto y quienes afirmaron trabajar mas en presencial.

In [226]:
remote_salary = df_remote['convertedcompyearly'].median()
remote_salary

82082.5

In [227]:
in_person_salary = df_in_person['convertedcompyearly'].median()
in_person_salary

62893.0

In [228]:
print(f'Un desarrollador que trabaja remoto o significativamente mas en remoto gana {remote_salary} dolares anuales.')
print(f'Un desarrollador que trabaja presencial o significativamente mas presencial gana {in_person_salary} dolares anuales.')
print(f'La diferencia es de {remote_salary - in_person_salary} dolares anuales en favor de los desarrolladores que trabajan significativamente mas en remoto.')

Un desarrollador que trabaja remoto o significativamente mas en remoto gana 82082.5 dolares anuales.
Un desarrollador que trabaja presencial o significativamente mas presencial gana 62893.0 dolares anuales.
La diferencia es de 19189.5 dolares anuales en favor de los desarrolladores que trabajan significativamente mas en remoto.

Otra solucion

In [229]:
df_clean = df[df['remotework'].notnull() & df['convertedcompyearly'].notnull()][['remotework', 'convertedcompyearly']]
df_clean.shape

(23947, 2)

In [230]:
df_clean[['remotework', 'convertedcompyearly']].isnull().sum()

remotework             0
convertedcompyearly    0
dtype: int64

In [231]:
salary_work_situation = df_clean.groupby('remotework')['convertedcompyearly'].agg(['median', 'count']).sort_values(by='median', ascending=False)
salary_work_situation

                                                     median  count
remotework
Remote                                              88492.0   7126
Hybrid (some in-person, leans heavy to flexibil...  80966.0   3815
Your choice (very flexible, you can come in whe...  75410.0   2753
Hybrid (some remote, leans heavy to in-person)      72958.0   4203
nan                                                 69609.0   2851
In-person                                           46406.0   3199