<a href="https://colab.research.google.com/github/mfernandezzz/Pruebas_Tecnicas/blob/main/TT_stackoverflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [258]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [259]:
df = pd.read_csv('/content/results.csv', low_memory=False)
schema = pd.read_csv('/content/schema.csv')
pd.set_option('display.max_columns', None)

In [260]:
schema.head()

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR

In [261]:
df.shape

(49191, 172)

In [262]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 357.8 MB

In [263]:
for i in df.select_dtypes('integer'):
  df[i] = pd.to_numeric(df[i], downcast='integer')

In [264]:
for f in df.select_dtypes('float'):
  df[f] = pd.to_numeric(df[f], downcast='float')

In [265]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(' ', '_')
)
df.columns

Index(['responseid', 'mainbranch', 'age', 'edlevel', 'employment',
       'employmentaddl', 'workexp', 'learncodechoose', 'learncode',
       'learncodeai',
       ...
       'aiagentorchestration', 'aiagentorchwrite', 'aiagentobservesecure',
       'aiagentobswrite', 'aiagentexternal', 'aiagentextwrite', 'aihuman',
       'aiopen', 'convertedcompyearly', 'jobsat'],
      dtype='object', length=172)

In [266]:
nulls_count = df.isnull().sum()
nulls_count[nulls_count > 0].sort_values(ascending=False)

aiagentobswrite      48927
sotagswant_entry     48761
sotagshaveentry      48733
aimodelswantentry    48716
aiagentorchwrite     48713
                     ...
employmentaddl        4316
learncodeai           3990
learncodechoose       2333
edlevel               1042
employment             852
Length: 169, dtype: int64

In [267]:
nulls_percentage = df.isnull().mean()*100
nulls_percentage[nulls_percentage > 0].sort_values(ascending=False)

aiagentobswrite      99.463316
sotagswant_entry     99.125856
sotagshaveentry      99.068935
aimodelswantentry    99.034376
aiagentorchwrite     99.028278
                       ...
employmentaddl        8.773963
learncodeai           8.111240
learncodechoose       4.742737
edlevel               2.118274
employment            1.732024
Length: 169, dtype: float64

In [268]:
duplicates_sum = df.duplicated().sum()
duplicates_sum

np.int64(0)

In [269]:
duplicates_percentage = (df.duplicated().sum()/df.shape[0]) * 100
duplicates_percentage

np.float64(0.0)

In [270]:
# show_duplicates = df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head()
# show_duplicates

In [271]:
# df = df.drop_duplicates()

In [272]:
# float_cols = df.select_dtypes(include=['float']).columns
# float_cols

In [273]:
# df[float_cols] = df[float_cols].fillna(0.0)

In [274]:
str_cols = df.select_dtypes(include=['object']).columns
str_cols

Index(['mainbranch', 'age', 'edlevel', 'employment', 'employmentaddl',
       'learncodechoose', 'learncode', 'learncodeai', 'ailearnhow', 'devtype',
       ...
       'aiagentknowledge', 'aiagentknowwrite', 'aiagentorchestration',
       'aiagentorchwrite', 'aiagentobservesecure', 'aiagentobswrite',
       'aiagentexternal', 'aiagentextwrite', 'aihuman', 'aiopen'],
      dtype='object', length=119)

In [275]:
df[str_cols] = df[str_cols].fillna('Unknown')

In [276]:
for c in df.select_dtypes('object'):
  df[c] = df[c].astype('category')

In [277]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, responseid to jobsat
dtypes: category(119), float32(50), float64(2), int32(1)
memory usage: 58.0 MB

**¿Python paga mas que JavaScript?**

In [278]:
df.head(4)

,responseid,mainbranch,age,edlevel,employment,employmentaddl,workexp,learncodechoose,learncode,learncodeai,ailearnhow,yearscode,devtype,orgsize,icorpm,remotework,purchaseinfluence,techendorseintro,techendorse_1,techendorse_2,techendorse_3,techendorse_4,techendorse_5,techendorse_6,techendorse_7,techendorse_8,techendorse_9,techendorse_13,techendorse_13_text,techoppose_1,techoppose_2,techoppose_3,techoppose_5,techoppose_7,techoppose_9,techoppose_11,techoppose_13,techoppose_16,techoppose_15,techoppose_15_text,industry,jobsatpoints_1,jobsatpoints_2,jobsatpoints_3,jobsatpoints_4,jobsatpoints_5,jobsatpoints_6,jobsatpoints_7,jobsatpoints_8,jobsatpoints_9,jobsatpoints_10,jobsatpoints_11,jobsatpoints_13,jobsatpoints_14,jobsatpoints_15,jobsatpoints_16,jobsatpoints_15_text,aithreat,newrole,toolcountwork,toolcountpersonal,country,currency,comptotal,languagechoice,languagehaveworkedwith,languagewanttoworkwith,languageadmired,languageshaveentry,languageswantentry,databasechoice,databasehaveworkedwith,databasewanttoworkwith,databaseadmired,databasehaveentry,databasewantentry,platformchoice,platformhaveworkedwith,platformwanttoworkwith,platformadmired,platformhaveentry,platformwantentry,webframechoice,webframehaveworkedwith,webframewanttoworkwith,webframeadmired,webframehaveentry,webframewantentry,devenvschoice,devenvshaveworkedwith,devenvswanttoworkwith,devenvsadmired,devenvhaveentry,devenvwantentry,sotagshaveworkedwith,sotagswanttoworkwith,sotagsadmired,sotagshaveentry,sotagswant_entry,opsyspersonal_use,opsysprofessional_use,officestackasynchaveworkedwith,officestackasyncwanttoworkwith,officestackasyncadmired,officestackhaveentry,officestackwantentry,commplatformhaveworkedwith,commplatformwanttoworkwith,commplatformadmired,commplatformhaveentr,commplatformwantentr,aimodelschoice,aimodelshaveworkedwith,aimodelswanttoworkwith,aimodelsadmired,aimodelshaveentry,aimodelswantentry,soaccount,sovisitfreq,soduration,sopartfreq,so_dev_content,so_actions_1,so_actions_16,so_actions_3,so_actions_4,so_actions_5,so_actions_6,so_actions_9,so_actions_7,so_actions_10,so_actions_15,so_actions_15_text,socomm,sofriction,aiselect,aisent,aiacc,aicomplex,aitoolcurrently_partially_ai,aitooldon't_plan_to_use_ai_for_this_task,aitoolplan_to_partially_use_ai,aitoolplan_to_mostly_use_ai,aitoolcurrently_mostly_ai,aifrustration,aiexplain,aiagents,aiagentchange,aiagent_uses,agentusesgeneral,aiagentimpactsomewhat_agree,aiagentimpactneutral,aiagentimpactsomewhat_disagree,aiagentimpactstrongly_agree,aiagentimpactstrongly_disagree,aiagentchallengesneutral,aiagentchallengessomewhat_disagree,aiagentchallengesstrongly_agree,aiagentchallengessomewhat_agree,aiagentchallengesstrongly_disagree,aiagentknowledge,aiagentknowwrite,aiagentorchestration,aiagentorchwrite,aiagentobservesecure,aiagentobswrite,aiagentexternal,aiagentextwrite,aihuman,aiopen,convertedcompyearly,jobsat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,Unknown,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,Unknown,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,Unknown,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,Unknown,Unknown,Yes,Cloud Firestore;PostgreSQL,Unknown,Unknown,Unknown,Unknown,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,Unknown,Unknown,Unknown,Unknown,No,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,Unknown,Unknown,"Stack Overflow;Reddit;GitHub (public projects,...",Unknown,Unknown,Unknown,Unknown,Yes,openAI GPT (chatbot models);openAI Image gener...,Unknown,Unknown,Unknown,Unknown,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Unknown,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,Unknown,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,Unknown,Unknown,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Unknown,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,Unknown,Unknown,Unknown,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,Unknown,Unknown,Unknown,Unknown,Vertex AI,Unknown,Unknown,Unknown,ChatGPT,Unknown,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,Unknown,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,Unknown,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,Unknown,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,Unknown,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,Unknown,Unknown,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,Unknown,Unknown,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Unknown,Unknown,Yes,Spring Boot,Spring Boot,Spring Boot,Unknown,Unknown,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Unknown,Unknown,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Unknown,Unknown,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),Unknown,Unknown,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,Unknown,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,Unknown,Unknown,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,It takes significant time and effort to learn ...,Unknown,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",Unknown,Unknown,Unknown,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,Unknown,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,Unknown,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,Unknown,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Unknown,Unknown,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,Unknown,Unknown,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,Unknown,Unknown,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,Unknown,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,Unknown,Unknown,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,Unknown,Unknown,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,Unknown,Unknown,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Unknown,Unknown,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,Unknown,Unknown,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,Unknown,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,Unknown,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,Unknown,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,Unknown,Unknown,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,Unknown,I am concerned about the accuracy of the infor...,Unknown,Redis,Unknown,Unknown,Unknown,Unknown,Unknown,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,Unknown,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,Unknown,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,Unknown,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,Unknown,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,Unknown,Unknown,No,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Unknown,Unknown,Yes,Spring Boot,Spring Boot,Spring Boot,Unknown,Unknown,No,Unknown,Unknown,Unknown,Unknown,Unknown,Amazon Bedrock,Unknown,Unknown,Unknown,Unknown,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,Unknown,Unknown,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,Unknown,Unknown,No,Unknown,Unknown,Unknown,Unknown,Unknown,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,Unknown,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,Unknown,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,Unknown,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,Unknown,Unknown,It takes significant time and effort to learn ...,Unknown,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,ChatGPT;Claude Code,Unknown,When I don’t trust AI’s answers;When I want to...,Unknown,36197.0,6.0

In [279]:
df[['languagehaveworkedwith', 'convertedcompyearly', 'currency']].dtypes

languagehaveworkedwith    category
convertedcompyearly        float64
currency                  category
dtype: object

In [280]:
df[['languagehaveworkedwith', 'convertedcompyearly', 'currency']].isna().sum()

languagehaveworkedwith        0
convertedcompyearly       25244
currency                      0
dtype: int64

In [281]:
mask_python = (df['languagehaveworkedwith'].str.contains('Python')) & (df['convertedcompyearly'].notna())
python_df = df[mask_python][['languagehaveworkedwith', 'convertedcompyearly']]
python_df.head(10)

                               languagehaveworkedwith  convertedcompyearly
4   C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...              60000.0
7   Bash/Shell (all shells);HTML/CSS;JavaScript;Py...              72000.0
8                                   Java;Python;Scala              70000.0
22       C#;C++;JavaScript;Python;Visual Basic (.Net)              87500.0
27                                 C#;Java;Python;SQL             209643.0
28              HTML/CSS;JavaScript;Python;TypeScript              78000.0
33                                      C#;Python;SQL             175000.0
37  Ada;Assembly;Bash/Shell (all shells);C;C#;C++;...             109000.0
40  HTML/CSS;Java;JavaScript;PHP;PowerShell;Python...              99999.0
41              HTML/CSS;JavaScript;Python;TypeScript             270000.0

In [282]:
python_df.shape

(12765, 2)

In [283]:
python_df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 12765 entries, 4 to 49106
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   languagehaveworkedwith  12765 non-null  category
 1   convertedcompyearly     12765 non-null  float64
dtypes: category(1), float64(1)
memory usage: 2.3 MB

In [284]:
mask_javascript = (df['languagehaveworkedwith'].str.contains('JavaScript')) & (df['convertedcompyearly'].notna())
javascript_df = df[mask_javascript][['languagehaveworkedwith', 'convertedcompyearly']]
javascript_df.head(4)

                              languagehaveworkedwith  convertedcompyearly
2                Dart;HTML/CSS;JavaScript;TypeScript              53061.0
4  C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...              60000.0
6                              JavaScript;TypeScript               6240.0
7  Bash/Shell (all shells);HTML/CSS;JavaScript;Py...              72000.0

In [285]:
javascript_df.shape

(14873, 2)

In [286]:
javascript_df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 14873 entries, 2 to 49105
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   languagehaveworkedwith  14873 non-null  category
 1   convertedcompyearly     14873 non-null  float64
dtypes: category(1), float64(1)
memory usage: 2.4 MB

In [287]:
python_df['convertedcompyearly'].agg(['mean', 'median'])

mean      100868.353937
median     76800.000000
Name: convertedcompyearly, dtype: float64

In [288]:
javascript_df['convertedcompyearly'].agg(['mean', 'median'])

mean      97086.730855
median    75410.000000
Name: convertedcompyearly, dtype: float64

Otra solucion

In [289]:
langs = ['Python', 'SQL', 'JavaScript', 'Rust', 'TypeScript']

In [290]:
df = df[(df['convertedcompyearly'].notna())]
df.shape

(23947, 172)

In [291]:
salarios = {}
for lang in langs:
  mask = df['languagehaveworkedwith'].str.contains(lang, na=False)

  salarios[lang] = (df[mask]['convertedcompyearly'].median())

  result = pd.Series(salarios)
  result = result.sort_values(ascending=False)

print('Salario medio por lenguage: ')
print(result.round(0))

Salario medio por lenguage:
Rust          83000.0
TypeScript    79648.0
Python        76800.0
SQL           76518.0
JavaScript    75410.0
dtype: float64

In [292]:
salarios

{'Python': 76800.0,
 'SQL': 76518.0,
 'JavaScript': 75410.0,
 'Rust': 83000.0,
 'TypeScript': 79647.5}

In [293]:
# .reindex(order)   metodo para ordenar los indices en base a el orden de los elementos de una lista

In [294]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 23947 entries, 0 to 49122
Columns: 172 entries, responseid to jobsat
dtypes: category(119), float32(50), float64(2), int32(1)
memory usage: 48.0 MB